### ISSUE TITLE
ST_Intersects does bbox comparison already

### ISSUE THREAD

**Issue by kannes** [astroidex/foss4g-europe-2018-workshop-postgresql-postgis-for-beginners-aemde#1]
Very nice! I scanned through it because I just had to teach PostGIS as well.

Noticed your ST_Intersects example using an explicit `&&`.

https://postgis.net/docs/ST_Intersects.html says 
> This function call will automatically include a bounding box comparison that will make use of any indexes that are available on the geometries.

so no && should be needed. This makes it easier for newbies. :)

Not sure which functions actually still require this in recent PostGIS versions.

**Comment by astroidex** [comment]
HI kannes, thanks for the feedback. Yes you are right with &&. I only wanted to show the participants that this && exists. But in this case it is not necessary.

**Comment by kannes** [comment]
:))
